//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winforms_mvp_tutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id_user { get; set; }
        public Nullable<int> fk_profile_id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual profile profile { get; set; }
    }
}
